# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.29.0
      hooks:
          - id: commitizen
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-json
    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.13.0
      hooks:
          - id: markdownlint-cli2
    - repo: local
      hooks:
          - id: lint
            name: lint
            entry: npm run lint
            language: system
            types: [text]
            files: "\\.(svelte|ts|js|json|css)$"
            pass_filenames: false
